import { createElement } from "react";
import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer";
import { resolveManagerTenantAgreementToken } from "@/server/services/manager-tenant-onboarding.service";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const revalidate = 0;

type ManagerAgreementDownloadRouteProps = {
  params: Promise<{
    token: string;
  }>;
};

const styles = StyleSheet.create({
  page: {
    padding: 42,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#111827",
    lineHeight: 1.55,
  },
  header: {
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#D1D5DB",
    borderBottomStyle: "solid",
  },
  brand: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1D4ED8",
    marginBottom: 4,
  },
  title: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#111827",
  },
  meta: {
    marginTop: 6,
    fontSize: 8,
    color: "#6B7280",
  },
  paragraph: {
    marginBottom: 7,
  },
  footer: {
    position: "absolute",
    left: 42,
    right: 42,
    bottom: 28,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    borderTopStyle: "solid",
    fontSize: 8,
    color: "#6B7280",
  },
});

function toSafePdfText(value: string) {
  return value.replace(/\u20A6/g, "NGN ");
}

function buildManagerAgreementPdf(params: {
  title: string;
  body: string;
  agreementId: string;
  status: string;
}) {
  const bodyLines = toSafePdfText(params.body)
    .split("\n")
    .map((line, index) =>
      createElement(
        Text,
        {
          key: `${index}-${line}`,
          style: styles.paragraph,
        },
        line || " ",
      ),
    );

  return createElement(
    Document,
    {
      title: params.title,
      author: "BOPA Manager",
      subject: "Tenancy Agreement",
    },
    createElement(
      Page,
      {
        size: "A4",
        style: styles.page,
      },
      createElement(
        View,
        {
          style: styles.header,
        },
        createElement(Text, { style: styles.brand }, "BOPA Manager"),
        createElement(Text, { style: styles.title }, params.title),
        createElement(
          Text,
          { style: styles.meta },
          `Agreement ID: ${params.agreementId} | Status: ${params.status}`,
        ),
      ),
      createElement(View, null, bodyLines),
      createElement(
        Text,
        {
          style: styles.footer,
        },
        "Generated by BOPA Manager. This document reflects the saved agreement record at the time of download.",
      ),
    ),
  );
}

export async function GET(
  _request: Request,
  { params }: ManagerAgreementDownloadRouteProps,
) {
  const { token } = await params;
  const agreement = await resolveManagerTenantAgreementToken(token);

  const agreementBody =
    agreement.finalized_body || agreement.agreement_body || "";

  const pdfBuffer = await renderToBuffer(
    buildManagerAgreementPdf({
      title: agreement.title,
      body: agreementBody,
      agreementId: agreement.id,
      status: agreement.document_status,
    }),
  );

  return new Response(new Uint8Array(pdfBuffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="bopa-manager-agreement-${agreement.id}.pdf"`,
      "Cache-Control": "private, no-store",
    },
  });
}
