import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer";
import { resolveManagerTenantAgreementToken } from "@/server/services/manager-tenant-onboarding.service";

type ManagerAgreementDownloadRouteProps = {
  params: Promise<{
    token: string;
  }>;
};

const styles = StyleSheet.create({
  page: {
    padding: 42,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#111827",
    lineHeight: 1.55,
  },
  header: {
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#D1D5DB",
    borderBottomStyle: "solid",
  },
  brand: {
    fontSize: 18,
    fontWeight: 700,
    color: "#1D4ED8",
    marginBottom: 4,
  },
  title: {
    fontSize: 14,
    fontWeight: 700,
    color: "#111827",
  },
  meta: {
    marginTop: 6,
    fontSize: 8,
    color: "#6B7280",
  },
  paragraph: {
    marginBottom: 7,
  },
  footer: {
    position: "absolute",
    left: 42,
    right: 42,
    bottom: 28,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    borderTopStyle: "solid",
    fontSize: 8,
    color: "#6B7280",
  },
});

function toSafeText(value: string) {
  return value.replace(/\u20A6/g, "NGN ");
}

function ManagerAgreementPdf({
  title,
  body,
  agreementId,
  status,
}: {
  title: string;
  body: string;
  agreementId: string;
  status: string;
}) {
  return (
    <Document
      title={title}
      author="BOPA Manager"
      subject="Tenancy Agreement"
    >
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>BOPA Manager</Text>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.meta}>
            Agreement ID: {agreementId} | Status: {status}
          </Text>
        </View>

        <View>
          {toSafeText(body)
            .split("\n")
            .map((line, index) => (
              <Text key={`${index}-${line}`} style={styles.paragraph}>
                {line || " "}
              </Text>
            ))}
        </View>

        <Text style={styles.footer}>
          Generated by BOPA Manager. This document reflects the saved agreement
          record at the time of download.
        </Text>
      </Page>
    </Document>
  );
}

export async function GET(
  _request: Request,
  { params }: ManagerAgreementDownloadRouteProps,
) {
  const { token } = await params;
  const agreement = await resolveManagerTenantAgreementToken(token);

  const pdfBuffer = await renderToBuffer(
    <ManagerAgreementPdf
      title={agreement.title}
      body={agreement.finalized_body || agreement.agreement_body}
      agreementId={agreement.id}
      status={agreement.document_status}
    />,
  );

  return new Response(pdfBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="bopa-manager-agreement-${agreement.id}.pdf"`,
      "Cache-Control": "private, no-store",
    },
  });
}