import "server-only";

import { AppError } from "@/server/errors/app-error";
import {
  createAgreementUsageEvent,
  createPublicGeneratedAgreement,
} from "@/server/repositories/public-agreement-generator.repository";
import { createPublicToolLead } from "@/server/repositories/public-tool-leads.repository";
import { createSupabaseAdminClient } from "@/server/supabase/admin";
import type {
  PublicAgreementDuration,
  PublicAgreementGeneratorInput,
  PublicAgreementRentFrequency,
  PublicAgreementUse,
} from "@/server/validators/public-agreement-generator.schema";

export type GeneratedPublicAgreementPreview = {
  leadId: string;
  agreementId: string;
  title: string;
  landlordFullName: string;
  tenantFullName: string;
  propertyLabel: string;
  rentAmount: number;
  rentFrequency: string;
  tenancyStartDate: string;
  tenancyEndDate: string;
  tenancyDurationMonths: number;
  agreementBody: string;
  watermarkText: string;
};

function addMonths(date: Date, months: number) {
  const result = new Date(
    Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()),
  );

  result.setUTCMonth(result.getUTCMonth() + months);

  return result;
}

function toDateOnly(value: Date) {
  return value.toISOString().slice(0, 10);
}

function formatDate(value: string | null) {
  if (!value) {
    return "____________________";
  }

  return new Intl.DateTimeFormat("en-NG", {
    dateStyle: "long",
  }).format(new Date(`${value}T00:00:00.000Z`));
}

function formatMoney(amount: number, currencyCode = "NGN") {
  return new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: currencyCode,
    maximumFractionDigits: 0,
  }).format(amount);
}

function calculateTenancyEndDate(
  startDate: string,
  duration: PublicAgreementDuration,
) {
  const start = new Date(`${startDate}T00:00:00.000Z`);

  if (Number.isNaN(start.getTime())) {
    throw new AppError(
      "INVALID_TENANCY_START_DATE",
      "Enter a valid tenancy start date.",
      400,
    );
  }

  const monthsByDuration: Record<PublicAgreementDuration, number> = {
    "6_months": 6,
    "1_year": 12,
    "2_years": 24,
  };

  const months = monthsByDuration[duration];
  const nextPeriodStart = addMonths(start, months);
  nextPeriodStart.setUTCDate(nextPeriodStart.getUTCDate() - 1);

  return {
    tenancyEndDate: toDateOnly(nextPeriodStart),
    tenancyDurationMonths: months,
  };
}

function cleanOptional(value: string | null | undefined) {
  const cleaned = value?.trim();

  return cleaned ? cleaned : null;
}

function rentFrequencyLabel(value: PublicAgreementRentFrequency) {
  const labels: Record<PublicAgreementRentFrequency, string> = {
    annual: "year",
    monthly: "month",
    quarterly: "quarter",
    biannual: "six months",
  };

  return labels[value];
}

function propertyUseLabel(value: PublicAgreementUse) {
  const labels: Record<PublicAgreementUse, string> = {
    residential: "residential purposes",
    commercial: "approved commercial purposes",
    mixed_use: "approved mixed residential and commercial purposes",
  };

  return labels[value];
}

function buildPropertyLabel(input: PublicAgreementGeneratorInput) {
  return [
    cleanOptional(input.propertyName),
    cleanOptional(input.unitIdentifier),
    input.propertyAddress,
    input.cityState,
  ]
    .filter(Boolean)
    .join(", ");
}

function buildPublicAgreementBody(params: {
  input: PublicAgreementGeneratorInput;
  tenancyEndDate: string;
}) {
  const landlordEmail =
    cleanOptional(params.input.landlordEmail) ?? "____________________";
  const tenantEmail =
    cleanOptional(params.input.tenantEmail) ?? "____________________";
  const propertyName =
    cleanOptional(params.input.propertyName) ?? "____________________";
  const specialTerms =
    cleanOptional(params.input.specialTerms) ?? "No special terms added.";
  const propertyRules =
    cleanOptional(params.input.propertyRules) ??
    "No additional property requirements were selected.";
  const cautionDepositText =
    params.input.cautionDepositAmount > 0
      ? `The Tenant shall pay a refundable caution/security deposit of ${formatMoney(
          params.input.cautionDepositAmount,
        )}.`
      : "The Tenant shall pay a refundable caution/security deposit where applicable.";

  return `TENANCY AGREEMENT

THIS TENANCY AGREEMENT is made on the date this document is generated by the Landlord.

BETWEEN:

LANDLORD:
${params.input.landlordFullName}
Phone Number: ${params.input.landlordPhoneNumber}
Email: ${landlordEmail}

AND

TENANT:
${params.input.tenantFullName}
Phone Number: ${params.input.tenantPhoneNumber}
Email: ${tenantEmail}

1. PREMISES

The Landlord lets to the Tenant the premises known as:

Property: ${propertyName}
Unit: ${params.input.unitIdentifier}
Address: ${params.input.propertyAddress}
Location: ${params.input.cityState}

2. TERM

The tenancy shall commence on ${formatDate(params.input.tenancyStartDate)}
and shall end on ${formatDate(params.tenancyEndDate)} unless renewed or terminated in accordance with this Agreement and applicable law.

3. RENT

The Tenant shall pay rent in the sum of ${formatMoney(
    params.input.rentAmount,
  )} per ${rentFrequencyLabel(params.input.rentFrequency)}.

Payment shall be due in accordance with the agreed payment frequency and the tenancy record maintained on BOPA (Boldverse Property).

4. CAUTION / SECURITY DEPOSIT

${cautionDepositText}

The deposit shall be refunded at the end of tenancy subject to:
- No damage beyond normal wear and tear
- No outstanding bills, rent, service charge, or other liabilities
- Compliance with all tenancy obligations
- Return of the premises in acceptable condition

5. USE OF PREMISES

The premises shall be used strictly for lawful ${propertyUseLabel(
    params.input.propertyUse,
  )} only.

The Tenant shall not use the premises for illegal, dangerous, nuisance-causing, or unauthorized activities.

6. PROPERTY REQUIREMENTS

The Tenant agrees to comply with the following property requirements selected for this premises:

${propertyRules}

7. TENANT’S OBLIGATIONS

The Tenant agrees to:
a. Pay rent promptly when due
b. Maintain the premises in good and tenantable condition
c. Keep the premises clean and safe
d. Not make structural alterations without the Landlord’s written consent
e. Not sublet, assign, or transfer possession without the Landlord’s written consent
f. Observe all estate, compound, community, and building rules
g. Pay utility bills and service charges assigned to the Tenant
h. Notify the Landlord promptly of major repairs or damage
i. Avoid causing nuisance, disturbance, or damage to other occupants or neighbours

8. LANDLORD’S OBLIGATIONS

The Landlord agrees to:
a. Ensure peaceful possession of the premises by the Tenant
b. Carry out structural repairs where necessary and where such repair is not caused by the Tenant
c. Not interfere unreasonably with the Tenant’s quiet enjoyment
d. Maintain records of rent payments and tenancy documents through BOPA (Boldverse Property) where applicable

9. UTILITIES / SERVICE CHARGES

Unless otherwise agreed in writing, the Tenant shall be responsible for electricity bills, water bills, waste disposal charges, estate dues, service charges, and other utilities consumed or assigned to the premises during the tenancy.

10. REPAIRS / DAMAGES

Any damage caused by the Tenant, the Tenant’s family, visitors, agents, or occupants beyond normal wear and tear shall be repaired at the Tenant’s cost.

The Landlord shall be responsible for structural repairs not caused by the Tenant.

11. INSPECTION

The Landlord or authorized agent may inspect the premises upon giving reasonable notice to the Tenant, except in emergencies.

12. TERMINATION / NOTICE TO QUIT

Either party may terminate this tenancy by giving the legally required notice in writing, subject to applicable Nigerian tenancy laws and any state-specific tenancy regulations.

13. BREACH / DEFAULT

Failure to pay rent when due, misuse of premises, unauthorized subletting, property damage, illegal activity, or breach of material terms may result in termination in accordance with applicable law.

14. GOVERNING LAW

This Agreement shall be governed by the laws of the Federal Republic of Nigeria and applicable state tenancy laws.

15. DIGITAL RECORD AND ACCEPTANCE

Where this Agreement is reviewed or accepted through BOPA (Boldverse Property), the digital acceptance record, timestamp, and stored document copy shall serve as evidence that the Tenant reviewed and accepted the terms. The parties may also print and sign a hard copy for physical record purposes.

16. SPECIAL TERMS

${specialTerms}

SIGNED:

_____________________________
LANDLORD / AGENT

Date: _______________________


_____________________________
TENANT

Date: _______________________


WITNESSES:

1. Name: ____________________
Signature: _________________

2. Name: ____________________
Signature: _________________
`;
}

export async function generatePublicTenancyAgreementPreview(
  input: PublicAgreementGeneratorInput,
): Promise<GeneratedPublicAgreementPreview> {
  const supabase = createSupabaseAdminClient();

  const { tenancyEndDate, tenancyDurationMonths } = calculateTenancyEndDate(
    input.tenancyStartDate,
    input.tenancyDuration,
  );

  const landlordEmail = cleanOptional(input.landlordEmail);
  const tenantEmail = cleanOptional(input.tenantEmail);
  const propertyName = cleanOptional(input.propertyName);
  const unitIdentifier = cleanOptional(input.unitIdentifier);
  const propertyLabel = buildPropertyLabel(input);
  const agreementTitle = "Tenancy Agreement";
  const agreementBody = buildPublicAgreementBody({
    input,
    tenancyEndDate,
  });

  const lead = await createPublicToolLead(supabase, {
    landlordFullName: input.landlordFullName,
    landlordPhoneNumber: input.landlordPhoneNumber,
    landlordEmail,
    sourceTool: "agreement",
    sourcePath: input.sourcePath,
    sourceLocation: null,
    metadata: {
      acquisition_channel: "public_agreement_generator",
      tenancy_duration: input.tenancyDuration,
      property_use: input.propertyUse,
    },
  });

  const agreementSnapshot = {
    title: agreementTitle,
    landlord_snapshot: {
      fullName: input.landlordFullName,
      phoneNumber: input.landlordPhoneNumber,
      email: landlordEmail,
    },
    tenant_snapshot: {
      fullName: input.tenantFullName,
      phoneNumber: input.tenantPhoneNumber,
      email: tenantEmail,
    },
    property_snapshot: {
      propertyName,
      address: input.propertyAddress,
      unitIdentifier,
      cityState: input.cityState,
      propertyUse: input.propertyUse,
    },
    tenancy_snapshot: {
      rentAmount: input.rentAmount,
      paymentFrequency: input.rentFrequency,
      currencyCode: "NGN",
      startDate: input.tenancyStartDate,
      endDate: tenancyEndDate,
      renewalNoticeDays: input.renewalNoticeDays,
      cautionDepositAmount: input.cautionDepositAmount,
    },
    agreement_body: agreementBody,
    watermark: "Generated with BOPA — boldverseproperty.com",
  };

  const agreement = await createPublicGeneratedAgreement(supabase, {
    leadId: lead.id,
    landlordFullName: input.landlordFullName,
    landlordPhoneNumber: input.landlordPhoneNumber,
    landlordEmail,
    tenantFullName: input.tenantFullName,
    tenantPhoneNumber: input.tenantPhoneNumber,
    propertyName,
    propertyAddress: input.propertyAddress,
    unitIdentifier,
    cityState: input.cityState,
    rentAmount: input.rentAmount,
    tenancyStartDate: input.tenancyStartDate,
    tenancyEndDate,
    tenancyDurationMonths,
    agreementTitle,
    agreementSnapshot,
    metadata: {
      acquisition_channel: "public_agreement_generator",
      rent_frequency: input.rentFrequency,
      property_use: input.propertyUse,
      caution_deposit_amount: input.cautionDepositAmount,
      renewal_notice_days: input.renewalNoticeDays,
    },
  });

  await createAgreementUsageEvent(supabase, {
    leadId: lead.id,
    agreementId: agreement.id,
    eventType: "agreement_generated",
    sourcePath: input.sourcePath,
    metadata: {
      tenancy_duration_months: tenancyDurationMonths,
      rent_amount: input.rentAmount,
      rent_frequency: input.rentFrequency,
      property_use: input.propertyUse,
    },
  });

  return {
    leadId: lead.id,
    agreementId: agreement.id,
    title: agreement.agreement_title,
    landlordFullName: agreement.landlord_full_name,
    tenantFullName: agreement.tenant_full_name,
    propertyLabel,
    rentAmount: Number(agreement.rent_amount),
    rentFrequency: rentFrequencyLabel(input.rentFrequency),
    tenancyStartDate: agreement.tenancy_start_date,
    tenancyEndDate: agreement.tenancy_end_date,
    tenancyDurationMonths: agreement.tenancy_duration_months,
    agreementBody,
    watermarkText: "Generated with BOPA — boldverseproperty.com",
  };
}
