import "server-only";

import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer";
import type { SupabaseClient } from "@supabase/supabase-js";
import { AppError } from "@/server/errors/app-error";
import type { QuitNoticeDetailRow } from "@/server/repositories/quit-notices.repository";
import { updateQuitNoticePdfPath } from "@/server/repositories/quit-notices.repository";
import { uploadQuitNoticePdf } from "@/server/services/storage.service";
import { buildQuitNoticeTemplate } from "@/server/services/quit-notice-template.service";

const styles = StyleSheet.create({
  page: {
    padding: 42,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#111827",
    lineHeight: 1.55,
  },
  header: {
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#D1D5DB",
    borderBottomStyle: "solid",
  },
  brand: {
    fontSize: 18,
    fontWeight: 700,
    color: "#1D4ED8",
    marginBottom: 4,
  },
  title: {
    fontSize: 14,
    fontWeight: 700,
    color: "#111827",
  },
  meta: {
    marginTop: 6,
    fontSize: 8,
    color: "#6B7280",
  },
  section: {
    marginBottom: 10,
  },
  paragraph: {
    marginBottom: 7,
  },
  footer: {
    position: "absolute",
    left: 42,
    right: 42,
    bottom: 28,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    borderTopStyle: "solid",
    fontSize: 8,
    color: "#6B7280",
  },
});

function getNoticeTitle(value: QuitNoticeDetailRow["notice_type"]) {
  if (value === "tenant_intent_to_vacate") {
    return "Tenant Notice of Intention to Vacate";
  }

  return "Notice to Quit";
}

function toSafeText(value: string) {
  return value.replace(/\u20A6/g, "NGN ");
}

function splitBody(value: string) {
  return toSafeText(value)
    .split("\n")
    .map((line) => line.trimEnd());
}

function QuitNoticePdfDocument({
  quitNotice,
}: {
  quitNotice: QuitNoticeDetailRow;
}) {
  const body = quitNotice.document_body || buildQuitNoticeTemplate(quitNotice);
  const title = getNoticeTitle(quitNotice.notice_type);

  return (
    <Document title={title} author="Boldverse Property" subject="Quit Notice">
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>Boldverse Property</Text>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.meta}>
            Notice ID: {quitNotice.id} | Status: {quitNotice.status} | Notice
            Date: {quitNotice.notice_date} | Vacate By:{" "}
            {quitNotice.vacate_by_date}
          </Text>
        </View>

        <View style={styles.section}>
          {splitBody(body).map((line, index) => (
            <Text key={`${line}-${index}`} style={styles.paragraph}>
              {line || " "}
            </Text>
          ))}
        </View>

        <Text style={styles.footer}>
          Generated by Boldverse Property. This document reflects the saved quit
          notice record at the time of generation. Vacancy is only confirmed
          through the formal move-out workflow.
        </Text>
      </Page>
    </Document>
  );
}

function createQuitNoticePdfPath(quitNotice: QuitNoticeDetailRow) {
  return [
    quitNotice.landlord_id,
    quitNotice.tenant_id,
    quitNotice.tenancy_id,
    `${quitNotice.id}.pdf`,
  ].join("/");
}

export async function generateAndStoreQuitNoticePdf(
  supabase: SupabaseClient,
  quitNotice: QuitNoticeDetailRow,
) {
  if (quitNotice.status === "withdrawn") {
    throw new AppError(
      "QUIT_NOTICE_WITHDRAWN",
      "A withdrawn quit notice cannot be generated as a PDF.",
      400,
    );
  }

  if (quitNotice.status === "expired") {
    throw new AppError(
      "QUIT_NOTICE_EXPIRED",
      "An expired quit notice cannot be generated as a PDF.",
      400,
    );
  }

  const pdfBuffer = await renderToBuffer(
    <QuitNoticePdfDocument quitNotice={quitNotice} />,
  );

  const pdfPath = createQuitNoticePdfPath(quitNotice);

  await uploadQuitNoticePdf({
    path: pdfPath,
    pdfBuffer,
  });

  return updateQuitNoticePdfPath(supabase, {
    quitNoticeId: quitNotice.id,
    pdfPath,
  });
}
