import "server-only";

import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer";
import type { RentPaymentRow } from "@/server/repositories/payments.repository";

const styles = StyleSheet.create({
  page: {
    padding: 42,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#111827",
    lineHeight: 1.5,
  },
  header: {
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#D1D5DB",
    borderBottomStyle: "solid",
  },
  brand: {
    fontSize: 18,
    fontWeight: 700,
    color: "#1D4ED8",
    marginBottom: 4,
  },
  title: {
    fontSize: 14,
    fontWeight: 700,
  },
  meta: {
    marginTop: 6,
    fontSize: 8,
    color: "#6B7280",
  },
  section: {
    marginBottom: 16,
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    borderBottomStyle: "solid",
    paddingVertical: 8,
  },
  label: {
    width: "38%",
    color: "#6B7280",
    fontWeight: 700,
  },
  value: {
    width: "62%",
    color: "#111827",
    fontWeight: 700,
  },
  amountBox: {
    marginTop: 12,
    padding: 14,
    backgroundColor: "#EFF6FF",
    borderRadius: 10,
  },
  amountLabel: {
    fontSize: 9,
    color: "#1D4ED8",
    fontWeight: 700,
    marginBottom: 5,
  },
  amountValue: {
    fontSize: 20,
    color: "#111827",
    fontWeight: 700,
  },
  footer: {
    position: "absolute",
    left: 42,
    right: 42,
    bottom: 28,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    borderTopStyle: "solid",
    fontSize: 8,
    color: "#6B7280",
  },
});

function formatPdfMoney(amount: number) {
  const formatted = new Intl.NumberFormat("en-NG", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);

  return `NGN ${formatted}`;
}

function formatDate(value: string | null) {
  if (!value) {
    return "Not provided";
  }

  return new Intl.DateTimeFormat("en-NG", {
    dateStyle: "medium",
  }).format(new Date(value));
}

function paymentMethodLabel(method: RentPaymentRow["payment_method"]) {
  if (method === "bank_transfer") {
    return "Bank Transfer";
  }

  if (method === "cash") {
    return "Cash";
  }

  if (method === "paystack_gateway") {
    return "Paystack";
  }

  return "Other";
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  );
}

function ReceiptPdfDocument({ payment }: { payment: RentPaymentRow }) {
  const propertyName =
    payment.tenancies?.units?.properties?.property_name ?? "Property";
  const unitIdentifier = payment.tenancies?.units?.unit_identifier ?? "Unit";
  const tenantName = payment.tenants?.full_name ?? "Tenant";

  return (
    <Document title="Rent Receipt" author="Tenuro" subject="Rent Receipt">
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>Tenuro</Text>
          <Text style={styles.title}>Rent Receipt</Text>
          <Text style={styles.meta}>
            Receipt No: {payment.receipt_number ?? "Pending"} | Payment ID:{" "}
            {payment.id}
          </Text>
        </View>

        <View style={styles.section}>
          <Row label="Tenant" value={tenantName} />
          <Row label="Property" value={propertyName} />
          <Row label="Unit" value={unitIdentifier} />
          <Row
            label="Tenancy Reference"
            value={payment.tenancies?.tenancy_reference ?? "Not provided"}
          />
          <Row
            label="Payment Method"
            value={paymentMethodLabel(payment.payment_method)}
          />
          <Row
            label="Payment Reference"
            value={payment.payment_reference ?? "Not provided"}
          />
          <Row label="Payment Date" value={formatDate(payment.payment_date)} />
          <Row
            label="Payment Period"
            value={`${formatDate(payment.payment_for_period_start)} - ${formatDate(
              payment.payment_for_period_end,
            )}`}
          />
          <Row
            label="Balance Before"
            value={formatPdfMoney(Number(payment.balance_before))}
          />
          <Row
            label="Balance After"
            value={formatPdfMoney(Number(payment.balance_after))}
          />
        </View>

        <View style={styles.amountBox}>
          <Text style={styles.amountLabel}>Amount Paid</Text>
          <Text style={styles.amountValue}>
            {formatPdfMoney(Number(payment.amount_paid))}
          </Text>
        </View>

        <Text style={styles.footer}>
          Generated by Tenuro. This receipt confirms that the payment above was
          recorded in the landlord rent ledger.
        </Text>
      </Page>
    </Document>
  );
}

export async function renderRentReceiptPdf(payment: RentPaymentRow) {
  return renderToBuffer(<ReceiptPdfDocument payment={payment} />);
}
