import "server-only";

import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer";
import { AppError } from "@/server/errors/app-error";
import type { TenancyAgreementDocumentRow } from "@/server/repositories/tenancy-agreements.repository";
import { updateTenancyAgreementPdfPath } from "@/server/repositories/tenancy-agreements.repository";
import type { SupabaseClient } from "@supabase/supabase-js";
import { uploadTenancyAgreementPdf } from "@/server/services/storage.service";

const styles = StyleSheet.create({
  page: {
    padding: 42,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#111827",
    lineHeight: 1.55,
  },
  header: {
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#D1D5DB",
    borderBottomStyle: "solid",
  },
  brand: {
    fontSize: 18,
    fontWeight: 700,
    color: "#1D4ED8",
    marginBottom: 4,
  },
  title: {
    fontSize: 14,
    fontWeight: 700,
    color: "#111827",
  },
  meta: {
    marginTop: 6,
    fontSize: 8,
    color: "#6B7280",
  },
  section: {
    marginBottom: 10,
  },
  paragraph: {
    marginBottom: 7,
  },
  footer: {
    position: "absolute",
    left: 42,
    right: 42,
    bottom: 28,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    borderTopStyle: "solid",
    fontSize: 8,
    color: "#6B7280",
  },
});

function toSafeText(value: string) {
  return value.replace(/\u20A6/g, "NGN ");
}

function splitBody(value: string) {
  return toSafeText(value)
    .split("\n")
    .map((line) => line.trimEnd());
}

function AgreementPdfDocument({
  agreement,
}: {
  agreement: TenancyAgreementDocumentRow;
}) {
  const acceptedAt = agreement.tenant_accepted_at
    ? new Intl.DateTimeFormat("en-NG", {
        dateStyle: "medium",
        timeStyle: "short",
      }).format(new Date(agreement.tenant_accepted_at))
    : "Not accepted yet";

  const body = agreement.finalized_body || agreement.agreement_body;

  return (
    <Document
      title={agreement.title}
      author="Tenuro"
      subject="Tenancy Agreement"
    >
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>Tenuro</Text>
          <Text style={styles.title}>{agreement.title}</Text>
          <Text style={styles.meta}>
            Agreement ID: {agreement.id} | Status: {agreement.document_status} |
            Accepted: {acceptedAt}
          </Text>
        </View>

        <View style={styles.section}>
          {splitBody(body).map((line, index) => (
            <Text key={`${line}-${index}`} style={styles.paragraph}>
              {line || " "}
            </Text>
          ))}
        </View>

        <Text style={styles.footer}>
          Generated by Tenuro. This copy reflects the saved agreement record and
          tenant digital acceptance status at the time of generation.
        </Text>
      </Page>
    </Document>
  );
}

function createPdfPath(agreement: TenancyAgreementDocumentRow) {
  return [
    agreement.landlord_id,
    agreement.tenant_id,
    agreement.tenancy_id,
    `${agreement.id}.pdf`,
  ].join("/");
}

export async function generateAndStoreTenancyAgreementPdf(
  supabase: SupabaseClient,
  agreement: TenancyAgreementDocumentRow,
) {
  if (
    agreement.document_status !== "sent_to_tenant" &&
    agreement.document_status !== "accepted"
  ) {
    throw new AppError(
      "AGREEMENT_PDF_NOT_READY",
      "Finalize the agreement before generating a PDF.",
      400,
    );
  }

  const pdfBuffer = await renderToBuffer(
    <AgreementPdfDocument agreement={agreement} />,
  );

  const pdfPath = createPdfPath(agreement);

  await uploadTenancyAgreementPdf({
    path: pdfPath,
    pdfBuffer,
  });

  return updateTenancyAgreementPdfPath(supabase, {
    agreementId: agreement.id,
    pdfPath,
  });
}
